
export const images = {
    image_bg: require("../assets/images/bg.png"),
    logo: require("../assets/images/logo.png"),
    hide_icon: require("../assets/images/hide.png"),
    show_icon: require("../assets/images/show.png"),
    linear_bg: require("../assets/images/linear_bg.png"),
    box_ut: require("../assets/images/box_ut.png"),
    history_ut: require("../assets/images/history_ut.png"),
    hub_ut: require("../assets/images/hub_ut.png"),
    duty_roster_ut: require("../assets/images/duty_roster_ut.png"),
    score_board_ut: require("../assets/images/score_board_ut.png"),
    score_board_ut_1: require("../assets/images/score_board_ut_1.png"),
    search: require("../assets/images/search.png"),
    setting_line: require("../assets/images/setting_line.png"),
    scan_btn: require("../assets/images/scan_btn.png"),
    scan_btn_ch: require("../assets/images/scan_btn_ch.png"),
    right_arrow: require("../assets/images/right_arrow.png"),
    file_dock: require("../assets/images/file_dock.png"),
    next_grey: require("../assets/images/next_grey.png"),
    prev_ic: require("../assets/images/prev_ic.png"),
    top_right_curve: require("../assets/images/top_right_curve.png"),
    top_left_curve: require("../assets/images/top_left_curve.png"),
    bottom_left_curve: require("../assets/images/bottom_left_curve.png"),
    bottom_right_curve: require("../assets/images/bottom_right_curve.png"),
    completed_ic: require("../assets/images/completed_ic.png"),
    circle_check_ic: require("../assets/images/circle_check_ic.png"),
    d_box_ic: require("../assets/images/3d_box_ic.png"),
    attach_ic: require("../assets/images/attach_ic.png"),
    qrcode_m: require("../assets/images/qrcode_m.png"),
    attbox: require("../assets/images/3d_box.png"),
    home_ic: require("../assets/images/home_ic.png"),
    accept_btn: require("../assets/images/accept_btn.png"),
    timestamp: require("../assets/images/timestamp.png"),
    remark: require("../assets/images/remark.png"),
    revise: require("../assets/images/revise.png"),
    dashboard_ic: require("../assets/images/dashboard_ic.png"),
    remove_ic: require("../assets/images/remove_ic.png"),
    dump_ic: require("../assets/images/dump_ic.png"),
    qr_code: require("../assets/images/qr_code.png"),
    close_white: require("../assets/images/close_white.png"),
    phone_ic: require("../assets/images/phone_ic.png"),
    accept_ic: require("../assets/images/accept_ic.png"),
    delievery_status: require("../assets/images/delievery_status.png"),
    share_ic: require("../assets/images/share_ic.png"),
    none_ic: require("../assets/images/none_ic.png"),
    header_gradient: require("../assets/images/header_gradient.png"),
    h_qrcode: require("../assets/images/h_qrcode.png"),
    c_qrcode: require("../assets/images/c_qrcode.png"),
    send_progress: require("../assets/images/send_progress.png"),
    link_scanned: require("../assets/images/link_scanned.png"),
    calendar_ic: require("../assets/images/calendar_ic.png"),
    down_arrow_ic: require("../assets/images/down_arrow.png"),
    search_empty: require("../assets/images/search_empty.png"),
    ch_accept: require("../assets/images/ch_accept.png"),
    ch_change_to_accept: require("../assets/images/ch_change_to_accept.png"),
    ch_scan_btn: require("../assets/images/ch_scan_btn.png"),
    round_close: require("../assets/images/round_close.png"),
    arrow_clockwise: require("../assets/images/arrow_clockwise.png"),
    // english introduction image
    P1: require("../assets/images/P1.png"),
    P2: require("../assets/images/P2.png"),
    P3: require("../assets/images/P3.png"),
    P4: require("../assets/images/P4.png"),
    P55: require("../assets/images/P55.png"),
    P5: require("../assets/images/P5.png"),
    P6: require("../assets/images/P6.png"),
    P7: require("../assets/images/P7.png"),
    P8: require("../assets/images/P8.png"),
    P9: require("../assets/images/P9.png"),
    P10: require("../assets/images/P10.png"),
    P11: require("../assets/images/P11.png"),
    P12: require("../assets/images/P12.png"),
    P13: require("../assets/images/P13.png"),
    P14: require("../assets/images/P14.png"),

    // chines introduction image
    P1_Chi: require("../assets/images/P1_Chi.png"),
    P2_Chi: require("../assets/images/P2_Chi.png"),
    P3_Chi: require("../assets/images/P3_Chi.png"),
    P4_Chi: require("../assets/images/P4_Chi.png"),
    P55_Chi: require("../assets/images/P55_Chi.png"),
    P5_Chi: require("../assets/images/P5_Chi.png"),
    P6_Chi: require("../assets/images/P6_Chi.png"),
    P7_Chi: require("../assets/images/P7_Chi.png"),
    P8_Chi: require("../assets/images/P8_Chi.png"),
    P9_Chi: require("../assets/images/P9_Chi.png"),
    P10_Chi: require("../assets/images/P10_Chi.png"),
    P11_Chi: require("../assets/images/P11_Chi.png"),
    P12_Chi: require("../assets/images/P12_Chi.png"),
    P13_Chi: require("../assets/images/P13_Chi.png"),
    P14_Chi: require("../assets/images/P14_Chi.png"),


    settings_gray: require("../assets/images/settings_gray.png"),
    scan_sf: require("../assets/images/scan_sf.png"),
    truck: require("../assets/images/truck.png"),
    union: require("../assets/images/Union.png"),

    batch_ic_unfinish: require("../assets/images/batch_ic_unfinish.png"),
    fleet_grey: require("../assets/images/fleet_grey.png"),
    process_grey: require("../assets/images/process_grey.png"),


    STW_1: require("../assets/images/STW_1.png"),
    STW_2: require("../assets/images/STW_2.png"),
    STW_3: require("../assets/images/STW_3.png"),


}