export const GET_DOCKETS = 'GET_DOCKETS'
export const GET_SHIPTODOCKETS = 'GET_SHIPTODOCKETS'
export const GET_DOCKET_HISTORY = 'GET_DOCKET_HISTORY'
export const GET_THIS_DOCKET = 'GET_THIS_DOCKET'
export const GET_THIS_LANGUAGE = 'GET_THIS_LANGUAGE'
export const GET_GLOBAL_SEARCH_DATA = 'GET_GLOBAL_SEARCH_DATA'

//Driver 
export const GET_ROSTER = 'GET_ROSTER'
export const GET_DRIVER_DOCKET = 'GET_DRIVER_DOCKET'
export const GET_PLANT_SCOREBOARD = 'GET_PLANT_SCOREBOARD'
export const GET_DRIVER_DOCKET_HISTORY = 'GET_DRIVER_DOCKET_HISTORY'
export const GET_SCOREBOARD = 'GET_SCOREBOARD'







