export const TYPE_SAVE_SELECTED_SCREEN = 'TYPE_SAVE_SELECTED_SCREEN'
export const TYPE_SAVE_USER_DATA = 'TYPE_SAVE_USER_DATA'
export const TYPE_CLEAR_USER_DATA = 'TYPE_CLEAR_USER_DATA'
export const TYPE_SAVE_CARD_DATA = 'TYPE_SAVE_CARD_DATA'
export const PHONE_VERIFICATION = 'PHONE_VERIFICATION'
export const APP_LOAD = 'APP_LOAD'

export const CUSTOMER_LOGIN = 'CUSTOMER_LOGIN'
export const APP_LOADER = 'APP_LOADER'


